name: dtt
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - async-timeout=4.0.1
  - attrs=21.4.0
  - blas=1.0
  - boto3=1.20.24
  - botocore=1.23.24
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.2.1
  - cachetools=4.2.2
  - catalogue=2.0.6
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - colorama=0.4.4
  - cryptography=36.0.0
  - cudatoolkit=11.3.1
  - cymem=2.0.5
  - cython-blis=0.7.4
  - dataclasses=0.8
  - ffmpeg=4.3
  - freetype=2.11.0
  - frozenlist=1.2.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - google-api-core=1.25.1
  - google-auth=1.33.0
  - google-cloud-core=1.7.1
  - google-cloud-storage=1.31.0
  - google-crc32c=1.1.2
  - google-resumable-media=1.3.1
  - googleapis-common-protos=1.53.0
  - grpcio=1.42.0
  - idna=3.3
  - intel-openmp=2021.4.0
  - jmespath=0.10.0
  - jpeg=9d
  - lame=3.100
  - langcodes=3.3.0
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libcrc32c=1.1.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libidn2=2.3.2
  - libpng=1.6.37
  - libprotobuf=3.19.1
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=5.2.0
  - murmurhash=1.0.5
  - ncurses=6.3
  - nettle=3.7.3
  - numpy=1.21.2
  - numpy-base=1.21.2
  - olefile=0.46
  - openh264=2.1.1
  - openssl=1.1.1m
  - packaging=21.3
  - pathy=0.6.0
  - pillow=8.4.0
  - pip=21.2.4
  - preshed=3.0.5
  - protobuf=3.19.1
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pydantic=1.8.2
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.9.7
  - python-dateutil=2.8.2
  - pytorch=1.10.2
  - pytorch-mutex=1.0
  - readline=8.1.2
  - requests=2.27.1
  - rsa=4.7.2
  - s3transfer=0.5.0
  - setuptools=58.0.4
  - shellingham=1.3.1
  - six=1.16.0
  - smart_open=5.1.0
  - spacy=3.2.1
  - spacy-legacy=3.0.8
  - spacy-loggers=1.0.1
  - sqlite=3.37.2
  - srsly=2.4.1
  - thinc=8.0.13
  - tk=8.6.11
  - torchaudio=0.10.2
  - torchtext=0.11.2
  - torchvision=0.11.3
  - typer=0.4.0
  - tzdata=2021e
  - urllib3=1.26.8
  - wasabi=0.8.2
  - wheel=0.37.1
  - xz=5.2.5
  - yarl=1.6.3
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - absl-py==1.0.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.5
    - backcall==0.2.0
    - bleach==4.1.0
    - cycler==0.11.0
    - datasets==2.4.0
    - debugpy==1.5.1
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dill==0.3.5.1
    - entrypoints==0.4
    - evaluate==0.3.0
    - executing==0.8.3
    - filelock==3.8.0
    - fonttools==4.32.0
    - fsspec==2022.7.1
    - google-auth-oauthlib==0.4.6
    - huggingface-hub==0.8.1
    - importlib-metadata==4.11.3
    - ipykernel==6.9.1
    - ipython==8.1.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.5
    - jedi==0.18.1
    - jinja2==3.0.3
    - joblib==1.1.0
    - jsonschema==4.4.0
    - jupyter==1.0.0
    - jupyter-client==7.1.2
    - jupyter-console==6.4.3
    - jupyter-core==4.9.2
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.2
    - kiwisolver==1.4.2
    - markdown==3.3.6
    - markupsafe==2.1.0
    - matplotlib==3.5.1
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - multiprocess==0.70.13
    - nbclient==0.5.12
    - nbconvert==6.4.2
    - nbformat==5.1.3
    - nest-asyncio==1.5.4
    - nltk==3.7
    - notebook==6.4.8
    - oauthlib==3.2.0
    - openai==0.26.5
    - pandas==1.4.1
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathlib2==2.3.7.post1
    - pathspec==0.5.5
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prometheus-client==0.13.1
    - prompt-toolkit==3.0.28
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==9.0.0
    - pydeprecate==0.3.2
    - pygments==2.14.0
    - pyparsing==3.0.7
    - pyrsistent==0.18.1
    - pytorch-lightning==1.7.3
    - pytz==2021.3
    - pyyaml==6.0
    - pyzmq==22.3.0
    - qtconsole==5.2.2
    - qtpy==2.0.1
    - regex==2022.3.15
    - requests-oauthlib==1.3.1
    - responses==0.18.0
    - rouge-score==0.1.2
    - scikit-learn==1.1.3
    - scipy==1.9.3
    - seaborn==0.12.2
    - send2trash==1.8.0
    - sentencepiece==0.1.97
    - sklearn==0.0
    - stack-data==0.2.0
    - tensorboard==2.10.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - terminado==0.13.3
    - testpath==0.6.0
    - threadpoolctl==3.1.0
    - tokenizers==0.12.1
    - torchmetrics==0.9.3
    - tornado==6.1
    - tqdm==4.63.0
    - traitlets==5.1.1
    - transformers==4.21.1
    - typing-extensions==4.3.0
    - unidecode==1.3.3
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==2.0.3
    - widgetsnbextension==3.5.2
    - xxhash==3.0.0
    - zipp==3.7.0
